apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: ctse-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ctse-app
  template:
    metadata:
      labels:
        app: ctse-app
    spec:
      containers:
      - name: customer-management-ms
        image: kvg99/customer_management_image:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 4000